// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACMucDU-97sAfF4MyB51fREf3z9ZW6fMA',
    appId: '1:306904529292:web:26a30e598aee5a8dff7ea9',
    messagingSenderId: '306904529292',
    projectId: 'suuq-staging-770c6',
    authDomain: 'suuq-staging-770c6.firebaseapp.com',
    storageBucket: 'suuq-staging-770c6.appspot.com',
    measurementId: 'G-TVF06MCNXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fH2zua6DB__rHsdHu-h1vqLjzUiWu3s',
    appId: '1:306904529292:android:d4e3e21c3d6e9007ff7ea9',
    messagingSenderId: '306904529292',
    projectId: 'suuq-staging-770c6',
    storageBucket: 'suuq-staging-770c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2fWP3_rWkVkzVRCiZm4ShtQ8I1h_lNA',
    appId: '1:306904529292:ios:ba9493206aab0f01ff7ea9',
    messagingSenderId: '306904529292',
    projectId: 'suuq-staging-770c6',
    storageBucket: 'suuq-staging-770c6.appspot.com',
    iosBundleId: 'com.suuq.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2fWP3_rWkVkzVRCiZm4ShtQ8I1h_lNA',
    appId: '1:306904529292:ios:9ec49f12acbca0cdff7ea9',
    messagingSenderId: '306904529292',
    projectId: 'suuq-staging-770c6',
    storageBucket: 'suuq-staging-770c6.appspot.com',
    iosBundleId: 'com.example.suuqIibiye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACMucDU-97sAfF4MyB51fREf3z9ZW6fMA',
    appId: '1:306904529292:web:fa912397e7fa8e1cff7ea9',
    messagingSenderId: '306904529292',
    projectId: 'suuq-staging-770c6',
    authDomain: 'suuq-staging-770c6.firebaseapp.com',
    storageBucket: 'suuq-staging-770c6.appspot.com',
    measurementId: 'G-TNHHNCV8DN',
  );
}
