// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsPnNI-UWRxv9KDCvnci5yb49SHBdcM9w',
    appId: '1:510650794585:web:695ff0ccebf60dafb3e748',
    messagingSenderId: '510650794585',
    projectId: 'suuq-b54e7',
    authDomain: 'suuq-b54e7.firebaseapp.com',
    storageBucket: 'suuq-b54e7.appspot.com',
    measurementId: 'G-PKH30X247K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKBNtzJlo0tiVomFoI8GhgogIW0Rn0T18',
    appId: '1:510650794585:android:cabda4856977d698b3e748',
    messagingSenderId: '510650794585',
    projectId: 'suuq-b54e7',
    storageBucket: 'suuq-b54e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvunvqNMvv4uRQVmqxD1xhofHk3N0paDY',
    appId: '1:510650794585:ios:4905609837b9abc8b3e748',
    messagingSenderId: '510650794585',
    projectId: 'suuq-b54e7',
    storageBucket: 'suuq-b54e7.appspot.com',
    iosBundleId: 'com.suuq.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvunvqNMvv4uRQVmqxD1xhofHk3N0paDY',
    appId: '1:510650794585:ios:618fc1d14db839d0b3e748',
    messagingSenderId: '510650794585',
    projectId: 'suuq-b54e7',
    storageBucket: 'suuq-b54e7.appspot.com',
    iosBundleId: 'com.example.suuqIibiye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsPnNI-UWRxv9KDCvnci5yb49SHBdcM9w',
    appId: '1:510650794585:web:aefd15f035758128b3e748',
    messagingSenderId: '510650794585',
    projectId: 'suuq-b54e7',
    authDomain: 'suuq-b54e7.firebaseapp.com',
    storageBucket: 'suuq-b54e7.appspot.com',
    measurementId: 'G-24NZ3KSPBT',
  );

}